### ISSUE TITLE
What version of Python was used?

### ISSUE THREAD

**Issue by ghost** [BNN-UPC/ENERO#2]
I used Python 3.7, but I encountered some issues when I obtained the figures following the instructions.

**Comment by ghost** [comment]
Like this problem

![image](https://user-images.githubusercontent.com/87467979/216828410-91d5ce76-5d0c-4763-bbd3-b97ceeec5091.png)

**Comment by paulalmasan** [comment]
There were some paths pointing to the wrong directory. I've solved this issue in https://github.com/BNN-UPC/ENERO/commit/84f1e76b159bb005504adfdea32a87445b6bebf3
